# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x05proto\"\t\n\x07Request\"&\n\x12TrackLocalResponse\x12\x10\n\x08trackIds\x18\x01 \x03(\t2R\n\x14GetTrackLocalService\x12:\n\rGetTrackLocal\x12\x0e.proto.Request\x1a\x19.proto.TrackLocalResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST']._serialized_start=24
  _globals['_REQUEST']._serialized_end=33
  _globals['_TRACKLOCALRESPONSE']._serialized_start=35
  _globals['_TRACKLOCALRESPONSE']._serialized_end=73
  _globals['_GETTRACKLOCALSERVICE']._serialized_start=75
  _globals['_GETTRACKLOCALSERVICE']._serialized_end=157
# @@protoc_insertion_point(module_scope)
